Change on mlhub.pkg
mlhubber/mlhub pull request #253
Opened 2021-10-10 23:18 UTC by davecatmeow

Change the behaviour of `pkg.mlask()` and `pkg.mlpreview()`, which are both crucial for current developing package.
- For `mlask`, mainly changing the waiting for Enter implementation from `input()` to an cross-platform `getChar()`, to avoid the non-response bug after `mlpreview`
- For `mlpreview`, now the defalt viewer would call system defalt application to open file.

2021-10-11 02:48 UTC, gjwgit requested changes
Testing suggests `mlask()` is no longer functional on terminal in Ubuntu. No input is accepted after the `Press Enter to continue:`

```
$ ml demo pyiris
=============================================
Python Machine Learning with the Iris Dataset
=============================================

Welcome to a demo of bulding machine learning models using Python. The
well known iris dataset is used. The dataset contains 150 observations
of iris flowers. Each observation records the petal and sepal width
and length in centimeters. Also recorded for each observation is the
species of the flower, being one of setosa, versicolor, and virginica.

The dataset is read in from a CSV (comma separated values) file, as
can be readily found on the Internet. This one comes from
https://access.togaware.com/iris.csv.

Press Enter to continue: 
Traceback (most recent call last):
  File "/home/gjw/.mlhub/pyiris/demo.py", line 66, in <module>
    mlask(end=True)
  File "/home/gjw/.local/lib/python3.9/site-packages/mlhub/pkg.py", line 262, in mlask
    answer = getChar()
  File "/home/gjw/.local/lib/python3.9/site-packages/mlhub/pkg.py", line 251, in getChar
    answer = sys.stdin.read(1)
KeyboardInterrupt
```

2021-10-11 10:35 UTC, davecatmeow commented
Thanks for the test, the bug is due to not properly handle the `"\n"` character. 
Now it shall be fixed, and I also tested the kmeans `demo.py` on the new mlhub.pkg

2021-10-16 03:09 UTC, gjwgit requested changes
In mlask() you may be able to use the original sys.stdout.write() but follow the first one with a sys.stdout.flush() to ensure the output is displayed on the terminal before the getChar() attempts to read. I am seeing the behaviour of having to type Enter before the previous message gets displayed.

2021-10-18 22:12 UTC, gjwgit commented
Manually resolved conflicts and merged.

2021-10-18 22:12 UTC, closed without merging